# Generated by Django 3.1.7 on 2021-03-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_auto_20210308_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='teste', max_length=50, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
