# Generated by Django 3.1.7 on 2021-03-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_auto_20210308_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='full name'),
        ),
    ]
